// <auto-generated />
namespace RealEstates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class whatChanges24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatChanges24));
        
        string IMigrationMetadata.Id
        {
            get { return "201909250943123_whatChanges24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
