// <auto-generated />
namespace RealEstates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class whatChanges9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatChanges9));
        
        string IMigrationMetadata.Id
        {
            get { return "201911191838187_whatChanges9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
